services:
  - type: web
    name: aces-verification
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd web_app && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: WHATSAPP_LINK_OFFICIAL
        sync: false
      - key: WHATSAPP_LINK_UNOFFICIAL
        sync: false
      - key: SECRET_KEY
        generateValue: true
